import { readFile, writeFile } from "node:fs/promises";
import { fileURLToPath } from "node:url";
import path from "node:path";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const schemaPath = path.join(root, "schema", "contracts.schema.json");
const outputPath = path.join(root, "src", "generated", "contracts.ts");
const schema = JSON.parse(await readFile(schemaPath, "utf8"));

const identifier = (value) =>
  /^[A-Za-z_$][A-Za-z0-9_$]*$/.test(value) ? value : JSON.stringify(value);

function typeFor(node, indent = "") {
  if (!node || typeof node !== "object") return "unknown";
  if (node.$ref) return node.$ref.slice(node.$ref.lastIndexOf("/") + 1);
  if (Object.hasOwn(node, "const")) return JSON.stringify(node.const);
  if (node.enum) return node.enum.map((value) => JSON.stringify(value)).join(" | ");
  if (node.oneOf) return node.oneOf.map((item) => typeFor(item, indent)).join(" | ");
  if (node.anyOf) return node.anyOf.map((item) => typeFor(item, indent)).join(" | ");

  if (Array.isArray(node.type)) {
    return node.type.map((type) => typeFor({ ...node, type }, indent)).join(" | ");
  }

  switch (node.type) {
    case "string":
      return "string";
    case "integer":
    case "number":
      return "number";
    case "boolean":
      return "boolean";
    case "null":
      return "null";
    case "array": {
      const itemType = typeFor(node.items ?? {}, `${indent}  `);
      return `readonly (${itemType})[]`;
    }
    case "object": {
      const properties = Object.entries(node.properties ?? {});
      if (properties.length === 0) {
        if (node.additionalProperties === true) return "Record<string, unknown>";
        if (node.additionalProperties && typeof node.additionalProperties === "object") {
          return `Record<string, ${typeFor(node.additionalProperties, indent)}>`;
        }
        return "Record<string, never>";
      }

      const required = new Set(node.required ?? []);
      const lines = properties.map(([key, value]) => {
        const optional = required.has(key) ? "" : "?";
        return `${indent}  readonly ${identifier(key)}${optional}: ${typeFor(value, `${indent}  `)};`;
      });
      return `{\n${lines.join("\n")}\n${indent}}`;
    }
    default:
      return "unknown";
  }
}

const names = Object.keys(schema.$defs);
const declarations = names.map((name) => {
  if (name !== "CommandEnvelope") {
    return `export type ${name} = ${typeFor(schema.$defs[name])};`;
  }

  const commandEnvelope = structuredClone(schema.$defs[name]);
  commandEnvelope.properties.command = { $ref: "#/$defs/TCommand" };
  return `export type CommandEnvelope<TCommand = BattleCommand> = ${typeFor(commandEnvelope)};`;
});

const mapLines = names.map((name) => {
  const typeName = name === "CommandEnvelope" ? "CommandEnvelope<BattleCommand>" : name;
  return `  readonly ${identifier(name)}: ${typeName};`;
});

const generated = `// Generated by scripts/generate-types.mjs from schema/contracts.schema.json.\n// Do not edit by hand.\n\n${declarations.join("\n\n")}\n\nexport const CONTRACT_SCHEMAS = ${JSON.stringify(schema.$defs, null, 2)} as const;\n\nexport type ContractName = keyof typeof CONTRACT_SCHEMAS;\n\nexport interface ContractTypeMap {\n${mapLines.join("\n")}\n}\n`;

if (process.argv.includes("--check")) {
  let current = "";
  try {
    current = await readFile(outputPath, "utf8");
  } catch {
    // The actionable message below is the same for a missing and stale output.
  }
  if (current !== generated) {
    console.error("Generated contracts are stale. Run `npm run generate`.");
    process.exitCode = 1;
  }
} else {
  await writeFile(outputPath, generated);
  console.log(`Generated ${names.length} contract types.`);
}
